
-- Добавляем примеры раскидок для карты Dust II
INSERT INTO public.grenade_throws (
  map_id, 
  name, 
  description, 
  grenade_type, 
  difficulty, 
  team, 
  throw_types,
  throw_point_x, 
  throw_point_y, 
  landing_point_x, 
  landing_point_y,
  media_type,
  video_url,
  is_public,
  is_verified
) VALUES 
-- Smoke на A site с тоннелей
((SELECT id FROM public.maps WHERE name = 'dust2'), 
 'Smoke A site из тоннелей', 
 'Блокирует обзор защитникам на A site', 
 'smoke', 
 'easy', 
 't', 
 '{standing}',
 15.5, 
 78.2, 
 25.8, 
 35.6,
 'video',
 'https://www.youtube.com/embed/dQw4w9WgXcQ',
 true,
 true),

-- Flash для выхода на A site
((SELECT id FROM public.maps WHERE name = 'dust2'), 
 'Pop-flash A site', 
 'Ослепляет защитников на A site при выходе', 
 'flash', 
 'medium', 
 't', 
 '{jump_throw}',
 18.3, 
 82.1, 
 27.4, 
 40.2,
 'video',
 'https://www.youtube.com/embed/dQw4w9WgXcQ',
 true,
 true),

-- HE граната на дефолт
((SELECT id FROM public.maps WHERE name = 'dust2'), 
 'HE на дефолт позицию', 
 'Наносит урон игрокам на стандартной позиции', 
 'he', 
 'hard', 
 'ct', 
 '{running_left, jump_throw}',
 45.2, 
 25.8, 
 38.9, 
 65.4,
 'video',
 'https://www.youtube.com/embed/dQw4w9WgXcQ',
 true,
 true),

-- Молотов для контроля тоннелей
((SELECT id FROM public.maps WHERE name = 'dust2'), 
 'Молотов тоннели', 
 'Блокирует проход через тоннели', 
 'molotov', 
 'medium', 
 'ct', 
 '{standing}',
 52.7, 
 48.3, 
 15.2, 
 75.6,
 'video',
 'https://www.youtube.com/embed/dQw4w9WgXcQ',
 true,
 true);

-- Добавляем примеры для карты Mirage
INSERT INTO public.grenade_throws (
  map_id, 
  name, 
  description, 
  grenade_type, 
  difficulty, 
  team, 
  throw_types,
  throw_point_x, 
  throw_point_y, 
  landing_point_x, 
  landing_point_y,
  media_type,
  video_url,
  is_public,
  is_verified
) VALUES 
-- Smoke на A site из раскопок
((SELECT id FROM public.maps WHERE name = 'mirage'), 
 'Smoke A site из раскопок', 
 'Перекрывает обзор с A site', 
 'smoke', 
 'easy', 
 't', 
 '{standing}',
 22.1, 
 85.4, 
 35.7, 
 42.3,
 'video',
 'https://www.youtube.com/embed/dQw4w9WgXcQ',
 true,
 true),

-- Flash для B раша
((SELECT id FROM public.maps WHERE name = 'mirage'), 
 'Flash B rush', 
 'Ослепляет защитников на B site', 
 'flash', 
 'easy', 
 't', 
 '{running_forward}',
 75.8, 
 82.1, 
 82.4, 
 65.7,
 'video',
 'https://www.youtube.com/embed/dQw4w9WgXcQ',
 true,
 true);
