// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mtevvmkvpxgxmazmzkfk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im10ZXZ2bWt2cHhneG1hem16a2ZrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4ODAwNDMsImV4cCI6MjA2NzQ1NjA0M30.kv_rEIyelYUF2b3Vh0bGKyMQBfO65Wby5DjKn-aiToE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});